<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLY6B2DF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLY6B2DF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLY6B2DF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLY6B2DF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLY6B2DF\App_KernelDevDebugContainer([
    'container.build_hash' => 'LY6B2DF',
    'container.build_id' => 'feccd93a',
    'container.build_time' => 1600894697,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLY6B2DF');
