<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPoYwMn9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPoYwMn9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPoYwMn9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPoYwMn9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPoYwMn9\App_KernelDevDebugContainer([
    'container.build_hash' => 'PoYwMn9',
    'container.build_id' => '5f3f49b7',
    'container.build_time' => 1601303805,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPoYwMn9');
